services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Umami\:
    resource: '../Classes/*'

  B13\Umami\Controller\StatisticsController:
    tags: ['backend.controller']
